(function () {
  "use strict";

  APP.dom = {
    referenceForm: document.getElementById("referenceForm"),
    referenceInput: document.getElementById("referenceInput"),
    passageText: document.getElementById("passageText"),
    translationSelect: document.getElementById("translationSelect"),
    perspectiveSelect: document.getElementById("perspectiveSelect"),
    analyzeButton: document.getElementById("analyzeButton"),

    historicalAnchor: document.getElementById("historicalAnchor"),
    customStartYear: document.getElementById("customStartYear"),
    customEndYear: document.getElementById("customEndYear"),
    continentSelect: document.getElementById("continentSelect"),
    regionSelect: document.getElementById("regionSelect"),
    compareRegions: document.getElementById("compareRegions"),
    regionalSearchButton: document.getElementById("regionalSearchButton"),

    useResearch: document.getElementById("useResearch"),
    researchTopic: document.getElementById("researchTopic"),
    sourceUrls: document.getElementById("sourceUrls"),
    maxSources: document.getElementById("maxSources"),

    useOllama: document.getElementById("useOllama"),
    llmSummaryLine: document.getElementById("llmSummaryLine"),

    openLlmSettings: document.getElementById("openLlmSettings"),
    llmDialog: document.getElementById("llmDialog"),
    llmProvider: document.getElementById("llmProvider"),
    ollamaEndpoint: document.getElementById("ollamaEndpoint"),
    ollamaModel: document.getElementById("ollamaModel"),
    llmModelOptions: document.getElementById("llmModelOptions"),
    llmRefreshModels: document.getElementById("llmRefreshModels"),
    llmApiKey: document.getElementById("llmApiKey"),
    testOllamaButton: document.getElementById("testOllamaButton"),
    llmDialogMessage: document.getElementById("llmDialogMessage"),

    tabAnalysis: document.getElementById("tabAnalysis"),
    tabTimeline: document.getElementById("tabTimeline"),
    analysisWorkspace: document.getElementById("analysisWorkspace"),
    timelineWorkspace: document.getElementById("timelineWorkspace"),
    exploreInTimeline: document.getElementById("exploreInTimeline"),

    formMessage: document.getElementById("formMessage"),
    connectionStatus: document.getElementById("connectionStatus"),
    referenceBadge: document.getElementById("referenceBadge"),

    emptyState: document.getElementById("emptyState"),
    resultContent: document.getElementById("resultContent"),
    passageSection: document.getElementById("passageSection"),
    passageTitle: document.getElementById("passageTitle"),
    passageContent: document.getElementById("passageContent"),
    soWhatSection: document.getElementById("soWhatSection"),
    soWhatContent: document.getElementById("soWhatContent"),
    blufContent: document.getElementById("blufContent"),
    historicalSettingContent: document.getElementById("historicalSettingContent"),
    applicationContent: document.getElementById("applicationContent"),
    timelineChart: document.getElementById("timelineChart"),
    regionalComparison: document.getElementById("regionalComparison"),
    biblicalEventsTable: document.getElementById("biblicalEventsTable"),
    worldEventsTable: document.getElementById("worldEventsTable"),
    sourcesTable: document.getElementById("sourcesTable"),
    methodNotes: document.getElementById("methodNotes"),

    metricsContent: document.getElementById("metricsContent"),
    auditLog: document.getElementById("auditLog")
  };

  APP.tdom = {
    form: document.getElementById("tlForm"),
    query: document.getElementById("tlQuery"),
    start: document.getElementById("tlStart"),
    end: document.getElementById("tlEnd"),
    continent: document.getElementById("tlContinent"),
    region: document.getElementById("tlRegion"),
    depth: document.getElementById("tlDepth"),
    providerOptions: document.getElementById("tlProviderOptions"),
    searxEndpoint: document.getElementById("tlSearxEndpoint"),
    urls: document.getElementById("tlUrls"),
    llmPlan: document.getElementById("tlLlmPlan"),
    llmExtract: document.getElementById("tlLlmExtract"),
    llmGapFill: document.getElementById("tlLlmGapFill"),
    llmLine: document.getElementById("tlLlmLine"),
    searchButton: document.getElementById("tlSearchButton"),
    stopButton: document.getElementById("tlStopButton"),
    formMessage: document.getElementById("tlFormMessage"),

    rangeBadge: document.getElementById("tlRangeBadge"),
    providerStatus: document.getElementById("tlProviderStatus"),
    planSummary: document.getElementById("tlPlanSummary"),
    empty: document.getElementById("tlEmpty"),
    results: document.getElementById("tlResults"),
    groupBy: document.getElementById("tlGroupBy"),
    filterText: document.getElementById("tlFilterText"),
    filterCategory: document.getElementById("tlFilterCategory"),
    filterConfidence: document.getElementById("tlFilterConfidence"),
    showUnverified: document.getElementById("tlShowUnverified"),
    zoomIn: document.getElementById("tlZoomIn"),
    zoomOut: document.getElementById("tlZoomOut"),
    zoomReset: document.getElementById("tlZoomReset"),
    viewLabel: document.getElementById("tlViewLabel"),
    chart: document.getElementById("tlChart"),
    legend: document.getElementById("tlLegend"),
    detail: document.getElementById("tlDetail"),
    laneSummary: document.getElementById("tlLaneSummary"),
    summarize: document.getElementById("tlSummarize"),
    summary: document.getElementById("tlSummary"),
    eventsHeading: document.getElementById("tlEventsHeading"),
    eventsTable: document.getElementById("tlEventsTable"),
    sourcesTable: document.getElementById("tlSourcesTable"),
    exportCsv: document.getElementById("tlExportCsv"),
    exportMd: document.getElementById("tlExportMd"),
    exportJson: document.getElementById("tlExportJson")
  };
}());